//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by: EnumGenerator.Core - 3.5.1214.0
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generated

open System.CodeDom.Compiler

[<GeneratedCode("EnumGenerator.Core", "3.5.1214.0")>]
type ExpensiveProducts =
    | Drill = 0
    | Hammer = 1
