//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by: EnumGenerator.Core - 0.1.920.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

[GeneratedCode("EnumGenerator.Core", "0.1.920.0")]
public enum ExpensiveProducts
{
    Drill = 0,

    Hammer = 1,
}
