//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by: EnumGenerator.Core - 3.3.1193.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

[GeneratedCode("EnumGenerator.Core", "3.3.1193.0")]
public enum ExpensiveProducts
{
    Drill = 0,

    Hammer = 1,
}
