''------------------------------------------------------------------------------
'' <auto-generated>
''     Generated by: EnumGenerator.Core - 4.0.1221.0
'' </auto-generated>
''------------------------------------------------------------------------------

Imports System.CodeDom.Compiler

<GeneratedCode("EnumGenerator.Core", "4.0.1221.0")>
Public Enum ExpensiveProducts
    Drill = 0
    Hammer = 1
End Enum
