''------------------------------------------------------------------------------
'' <auto-generated>
''     Generated by: EnumGenerator.Core - 3.5.1214.0
'' </auto-generated>
''------------------------------------------------------------------------------

Imports System.CodeDom.Compiler

<GeneratedCode("EnumGenerator.Core", "3.5.1214.0")>
Public Enum ExpensiveProducts
    Drill = 0
    Hammer = 1
End Enum
