//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by: EnumGenerator.Core - 4.0.1221.0
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generated

open System.CodeDom.Compiler

[<GeneratedCode("EnumGenerator.Core", "4.0.1221.0")>]
type ExpensiveProducts =
    | Drill = 0
    | Hammer = 1
