//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by: EnumGenerator.Core - 3.0.1187.0
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Example
{
    /// <summary>
    /// Enum with all the months.
    /// </summary>
    [GeneratedCode("EnumGenerator.Core", "3.0.1187.0")]
    public enum Months
    {
        /// <summary>
        /// Janus is the Roman god of gates and doorways, depicted with two faces looking in opposite directions. His festival month is January.
        /// </summary>
        January = 1,

        /// <summary>
        /// Februarius had 28 days, until circa 450 BC when it had 23 or 24 days on some of every second year, until Julius when it had 29 days on every fourth year and 28 days otherwise.
        /// </summary>
        February = 2,

        /// <summary>
        /// March was the original beginning of the year, and the time for the resumption of war.
        /// </summary>
        March = 3,

        /// <summary>
        /// Aprilis had 30 days, until Numa when it had 29 days, until Julius when it became 30 days long.
        /// </summary>
        April = 4,

        /// <summary>
        /// Maia (meaning 'the great one') is the Italic goddess of spring, the daughter of Faunus, and wife of Vulcan.
        /// </summary>
        May = 5,

        /// <summary>
        /// Juno is the principle goddess of the Roman Pantheon. She is the goddess of marriage and the well-being of women. She is the wife and sister of Jupiter. She is identified with the Greek goddess Hera.
        /// </summary>
        June = 6,

        /// <summary>
        /// Julius Caesar reformed the Roman calendar (hence the Julian calendar) in 46 BC. In the process, he renamed this month after himself.
        /// </summary>
        July = 7,

        /// <summary>
        /// Augustus Caesar clarified and completed the calendar reform of Julius Caesar. In the process, he also renamed this month after himself.
        /// </summary>
        August = 8,

        /// <summary>
        /// September had 30 days, until Numa when it had 29 days, until Julius when it became 30 days long.
        /// </summary>
        September = 9,

        /// <summary>
        /// October has always had 31 days.
        /// </summary>
        October = 10,

        /// <summary>
        /// October has always had 31 days.
        /// </summary>
        November = 11,

        /// <summary>
        /// December had 30 days, until Numa when it had 29 days, until Julius when it became 31 days long.
        /// </summary>
        December = 12,
    }
}
