//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by: EnumGenerator.Core - 3.4.1206.0
// </auto-generated>
//------------------------------------------------------------------------------

namespace Example

open System.CodeDom.Compiler

/// <summary>
/// Enum with all the months.
/// </summary>
[<GeneratedCode("EnumGenerator.Core", "3.4.1206.0")>]
type Months =
    | January = 1
    | February = 2
    | March = 3
    | April = 4
    | May = 5
    | June = 6
    | July = 7
    | August = 8
    | September = 9
    | October = 10
    | November = 11
    | December = 12
